# Generated by Django 2.0.2 on 2018-04-24 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180325_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 4, 24, 12, 52, 12, 945860), verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 4, 24, 12, 52, 12, 946860), verbose_name='Дата публікації'),
        ),
    ]
