"""
Django settings for myhive project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7%+=_yfb@p(6p#lh)jrm9_qe5(2=t3&*#6%v5b&5dp*owvupt)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'sslserver',
    'django.contrib.admin',
    'registration',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'default',
    'guestbook',
    'news',
    'good',
    'users',
    'blog',
    'social_django',


]

SECURE_SSL_REDIRECT =False

ACCOUNT_ACTIVATION_DAYS = 1
REGISTRATION_AUTO_LOGIN = True
SIMPLE_BACKEND_REDIRECT_URL = '/default/'
LOGIN_REDIRECT_URL = '/default/'


ADMIN_EMAIL = 'admin@studentsdb.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '465'
EMAIL_HOST_USER = 'witaly95@gmail.com'
EMAIL_HOST_PASSWORD = 'Witalya19950425q'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware' ,
]

ROOT_URLCONF = 'myhive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = ('social_core.backends.github.GithubOAuth2', 'social_core.backends.twitter.TwitterOAuth',
                           'social_core.backends.facebook.FacebookOAuth2', 'django.contrib.auth.backends.ModelBackend',
                           'social_core.backends.instagram.InstagramOAuth2',)

SOCIAL_AUTH_FACEBOOK_KEY = '627374324277043'
SOCIAL_AUTH_FACEBOOK_SECRET = '917eef07e5be133197e03c0a009b1959'
SOCIAL_AUTH_FACEBOOK_REDIRECT_URI = 'https://localhost:8000/oauth/complete/facebook/'

SOCIAL_AUTH_GITHUB_KEY = 'b654b61630b4b9a51765'
SOCIAL_AUTH_GITHUB_SECRET = 'e899848ff0dfd25639403cb21e04114b06f764d0'

SOCIAL_AUTH_INSTAGRAM_KEY = '78998337dc3948a9b5a00a4c9ddbd934'
SOCIAL_AUTH_INSTAGRAM_SECRET = '5ba777633fb14423a528c80936e49809'
#SOCIAL_AUTH_INSTAGRAM_AUTH_EXTRA_ARGUMENTS = {'scope': 'likes comments relationships' }
SOCIAL_AUTH_INSTAGRAM_REDIRECT_URL = 'https://localhost:8000/oauth/complete/instagram/'





WSGI_APPLICATION = 'myhive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
MEDIA_URL = '/media/'
MEDIA_ROOT = (os.path.join(BASE_DIR, '..', 'media'))
