# Generated by Django 2.0.2 on 2018-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Користувач')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Публікація')),
                ('content', models.TextField(verbose_name='Зміст')),
            ],
            options={
                'ordering': ['-posted'],
                'verbose_name_plural': 'записи гостьової книги',
                'verbose_name': 'запис гостьової книги',
            },
        ),
    ]
