# Generated by Django 2.0.2 on 2018-02-28 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Короткий опис')),
                ('content', models.TextField(verbose_name='Повен зміст')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2018, 2, 28, 18, 4, 25, 58135), verbose_name='Публікація')),
            ],
            options={
                'verbose_name_plural': 'новини',
                'ordering': ['-posted'],
                'verbose_name': 'новина',
            },
        ),
    ]
