# Generated by Django 2.0.2 on 2018-03-01 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 1, 16, 53, 0, 966900), verbose_name='Публікація'),
        ),
    ]
