# Generated by Django 2.0.2 on 2018-03-16 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180301_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 16, 21, 47, 34, 943000), verbose_name='Публікація'),
        ),
    ]
