# Generated by Django 2.0.2 on 2018-03-16 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180316_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 16, 22, 3, 22, 22737), verbose_name='Публікація'),
        ),
    ]
