# Generated by Django 2.0.2 on 2018-03-16 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180316_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 16, 22, 4, 6, 931343), verbose_name='Публікація'),
        ),
    ]
