# Generated by Django 2.0.2 on 2018-03-18 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180316_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 18, 19, 44, 28, 950611), verbose_name='Публікація'),
        ),
    ]
