# Generated by Django 2.0.2 on 2018-03-19 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180318_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 19, 20, 32, 47, 67541), verbose_name='Публікація'),
        ),
    ]
