# Generated by Django 2.0.2 on 2018-03-24 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180319_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 24, 21, 21, 42, 694935), verbose_name='Публікація'),
        ),
    ]
