# Generated by Django 2.0.2 on 2018-03-24 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180324_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 24, 21, 55, 42, 520393), verbose_name='Публікація'),
        ),
    ]
