# Generated by Django 2.0.2 on 2018-04-24 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180325_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 4, 24, 12, 52, 12, 924286), verbose_name='Публікація'),
        ),
    ]
