# Generated by Django 2.0.2 on 2018-05-05 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20180424_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 5, 23, 37, 36, 543009), verbose_name='Публікація'),
        ),
    ]
