# Generated by Django 2.0.2 on 2018-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Назва')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковий номер')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'категорії',
                'verbose_name': 'категорія',
            },
        ),
    ]
