# Generated by Django 2.0.2 on 2018-03-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
