# Generated by Django 2.0.2 on 2018-03-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_auto_20180316_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Короткий опис')),
                ('content', models.TextField(verbose_name='Повний опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='Фото')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.Category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name_plural': 'Товари',
                'verbose_name': 'Товар',
                'ordering': ['name'],
            },
        ),
    ]
